server:
  port: 8087
app:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl10GzX2T4ZmMkf2OlsS1XAiTu/flKYAzyHowKgg6436FUlZZ0jV9HH635+oMjSC3tu1xMUF6UnUebCU9k1kkZxS+q3p2NPSaWkpKC67ZCAidi2w/iIXkIrcpuRE5vF6N1crzdWH4EDySuiG4nIfag2uEMGjms5YlMX+ONJKvy6NKpK27CTwUv6F0h0P2LSrqZXwxhyGxDdeuO+qACB+nvfVyiEL0KMYeLECp0gYKm+dJL8Hfa+X5vpVzE8lz1GOYlJg2z2U6n4w9RDaFd2cxlJhIkqdJUwj90hdCm20BWY5Xex0S/R0RyShjA8eiFeTvpezWbhYjyvja11/3kB6VrQIDAQAB

