spring:
  datasource:
    url: jdbc:h2:mem:clsb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
  mail:
    host: tilleuls.messio.com
    port: 22225
    username: jpc
    password: jp33ere
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com.messio.gate: DEBUG
app:
  mirror-name: __MIRROR__
  identity:
    jwk-set-url: https://gate.messio.com/auth/keys
    base-url: https://gate.messio.com
    client-id: 48c75db4-405a-4f2f-a149-7036db6b6418
    client-secret: secret_for_clsb

