drop table if exists accounts CASCADE
drop table if exists banks CASCADE
drop table if exists currencies CASCADE
create table accounts (id bigint generated by default as identity, collateral varchar(255) not null, denomination varchar(255) not null, eligible boolean not null, short_limit varchar(255) not null, suspended boolean not null, bank_id bigint, primary key (id))
create table banks (id bigint generated by default as identity, closing time not null, denomination varchar(255) not null, minimum_pay_in varchar(255) not null, mirror varchar(255) not null, opening time not null, settlement_completion_target time not null, primary key (id))
create table currencies (id bigint generated by default as identity, close time not null, closing time not null, currency_group varchar(255) not null, funding_completion_target time not null, iso varchar(255) not null, opening time not null, bank_id bigint, primary key (id))
alter table accounts add constraint UK_pa38jvjxu0xfd18g735d06wd4 unique (denomination)
alter table banks add constraint UK_3ayyw8thxtia4g23btpyvfgqj unique (denomination)
alter table currencies add constraint UK_gfongft0igw84ed7kt3lbwv1c unique (iso)
alter table accounts add constraint FKb78evw9x9jyy66ld572kl8rgx foreign key (bank_id) references banks
alter table currencies add constraint FKd3ei4ijm3gw4xta4xtx4w3fwm foreign key (bank_id) references banks